### ISSUE TITLE
error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by anandhu-eng** [jjmachan/Looper#1]
The code was run on Ubuntu 20.04.2 LTS. 
The required modules specified in the readme file was installed in the system.
I am attaching a screen shot of the full error message.
![Screenshot from 2021-03-22 00-14-31](https://user-images.githubusercontent.com/71482562/111916985-9dff7900-8aa3-11eb-9cf9-62f635cfeee1.png)

**Comment by jjmachan** [comment]
I guess it's because the camer has not been detected
got into the file and you see `videocapture()` function. It expects an integer. Try something like 0 

Also how many webcams do you have connected to your system?

**Comment by anandhu-eng** [comment]
yeah got it!
i have only one webcam connected and that too my laptops camera.

**Comment by jjmachan** [comment]
great to hear that @anandhu-eng !

**Comment by jjmachan** [comment]
this was just a quick project but I'm glad you found this interesting enough 😄

**Comment by anandhu-eng** [comment]
I found it bit a creative work though 😃 ....Thanks for responding to the doubt @jjmachan :)

**Comment by jjmachan** [comment]
my pleasure! Thanks for the nice words too 😄
